users:
    - id: 5f5157ba-61a2-4bd9-a763-90076442a166
      username: guest
      fullName: Guest
      password: $2a$10$kxyNmDMbVv8Vm9R8uoreJ.p2.r5.sU3EYiUa7ztaut4mogIuPekDC # 'guest'
      email: guest@guest.com
    - id: 7fcf7c51-7439-4d40-a5c4-b9a4f2c9a1ba
      username: tombenke
      fullName: Tam√°s Benke
      password: $2a$10$JIirNkgpqwjUK8ojkRpUY.zMRLZ8v44SxkYlEnIZtdmM5YRdy0bhW # 'secret'
      email: tombenke@gmail.com
